---
- name: Install Postgres
  apt: name={{ item }} state=present
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev

- name: Start Postgres service
  service: name=postgresql enabled=yes state=started

# sudo -u postgres createuser -d -P videouploader