---
- hosts: all
  tasks:
    - block:
      - name: Run the equivalent of "apt-get update" as a separate step
        apt: update_cache=yes
      - name: Copy working files
        copy: src=working dest=/root/
      - name: Install Nginx with Upload module
        script: scripts/install_nginx_uploader.sh
        args:
          creates: /opt/nginx/sbin/nginx
      - name: Install Nginx service
        copy: src=config/nginx.service dest=/lib/systemd/system/nginx.service
      - name: Enable Nginx service
        service: name=nginx enabled=yes
      - name: Install PHP 7.0
        include: php7.yml
      - name: Install Ruby
        include: ruby.yml
      - name: Replaces Nginx conf file
        template: src=config/nginx_uploader.conf.j2 dest=/opt/nginx/conf/nginx.conf
        notify: restart_nginx
      - name: Prepares upload folders
        file: dest=/tmp/{{ item }} state=directory mode=0777
        with_items: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
      - name: Prepares working folder
        file: dest=/var/esg-videos state=directory mode=0777
      become: yes
      become_method: sudo
  handlers:
    - name: restart_nginx
      service: name=nginx enabled=yes state=restarted
      become: yes
      become_method: sudo
    - name: restart_php_fpm
      service: name=php7.0-fpm enabled=yes state=restarted
      become: yes
      become_method: sudo
